FROM node:20-alpine AS builder
WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .

ARG VITE_API_URL
ARG VITE_PEER_HOST
ARG VITE_PEER_PORT
ARG VITE_PEER_PATH
ARG VITE_PEER_SECURE


ENV VITE_API_URL=$VITE_API_URL
ENV VITE_PEER_HOST=$VITE_PEER_HOST
ENV VITE_PEER_PORT=$VITE_PEER_PORT
ENV VITE_PEER_PATH=$VITE_PEER_PATH
ENV VITE_PEER_SECURE=$VITE_PEER_SECURE

RUN npm run build

FROM nginx:stable-alpine AS run
COPY --from=builder /frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]