apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secrets
type: Opaque
stringData:
  NODE_ENV: 'development'
  PORT: '5000'
  # Kết nối ra Docker Desktop bên ngoài
  MONGO_URI: 'mongodb://admin:123456@mongo-service:27017/chat_app?authSource=admin'
  MONGO_USER: 'admin'
  MONGO_PASS: '123456'
  REDIS_URL: 'redis://redis-service:6379'
  REDIS_HOST: 'host.docker.internal'
  REDIS_PORT: '6379'
  REDIS_MODE: 'standalone'
  # Bảo mật
  JWT_SECRET: 'secret_jwt'
  JWT_EXPIRES_IN: '7d'
  FRONTEND_ORIGIN: 'http://localhost:5173'
  # Cloudinary (Biến đang gây lỗi Crash)
  CLOUDINARY_CLOUD_NAME: 'dghi1pwna'
  CLOUDINARY_API_KEY: '231888562827677'
  CLOUDINARY_API_SECRET: 'XORbzPukos5QrWwl6Mw5BKEFSIc'
