apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer # Dùng để lấy IP truy cập từ trình duyệt
  selector:
    app: chat-backend
  ports:
    - protocol: TCP
      port: 80 # Cổng bên ngoài người dùng gọi vào
      targetPort: 5000 # Cổng chạy bên trong container
