[build]
  dockerfile = "Dockerfile"

[processes]
  app = "node dist/index.js"    # Đây là Web Server (Express)
  worker = "node dist/worker.js" # Đây là Background Worker

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"] # Chỉ cho phép process "app" nhận traffic HTTP