# --- BACKEND DEPLOYMENT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: backend-container
          image: leanhtu23131/chat-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: chat-app-secrets

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

---
# --- FRONTEND DEPLOYMENT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: frontend-container
          image: leanhtu23131/chat-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
# --- WORKER DEPLOYMENT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-worker
  template:
    metadata:
      labels:
        app: chat-worker
    spec:
      containers:
        - name: worker-container
          image: leanhtu23131/chat-backend
          imagePullPolicy: IfNotPresent
          command: ['node', 'dist/worker.js']
          envFrom:
            - secretRef:
                name: chat-app-secrets
