# --- FRONTEND SERVICE ---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: chat-frontend
  ports:
    - port: 80
      targetPort: 80

---
# --- BACKEND SERVICE ---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: chat-backend
  ports:
    - port: 5000
      targetPort: 5000
