# --- FRONTEND SERVICE ---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: chat-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# --- BACKEND SERVICE ---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: chat-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
