name: Build and Deploy to Kubernetes

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- BUILD & PUSH BACKEND ---
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-backend:lastest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-backend:lastest

      # --- BUILD & PUSH FRONTEND ---
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-frontend:lastest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-frontend:lastest

      # --- SET K8S CONTEXT ---
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # --- SETUP KUSTOMIZE ---
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: 'v5.0.0'

      # --- UPDATE IMAGE TAG IN KUSTOMIZE ---
      - name: Update image tag
        run: |
          cd k8s
          kustomize edit set image leanhtu23131/chat-backend=${{ secrets.DOCKER_USERNAME }}/chat-backend:lastest
          kustomize edit set image leanhtu23131/chat-frontend=${{ secrets.DOCKER_USERNAME }}/chat-frontend:lastest

      # --- DEPLOY ---
      - name: Deploy
        run: |
          kubectl apply -k k8s --validate=false
          kubectl rollout status deployment backend-deployment
          kubectl rollout status deployment frontend-deployment
